django/django_book1/blog/urls.py
from django.urls import (path, re_path)

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    re_path(
        r'^post/(?P<slug>[-\w]+)/$', views.PostDetailView.as_view(), 
        name='post_detail'
    ),   
    path('archive/', views.PostArchiveView.as_view(), name='post_archive'),
    path(
        'archive/<int:year>/', views.PostYearArchiveView.as_view(),
        name='post_year_archive'
    ),
    path(
        'archive/<int:year>/<str:month>/', 
        views.PostMonthArchiveView.as_view(), 
        name='post_month_archive'
    ),
    path(
        'archive/<int:year>/<str:month>/<int:day>/', 
        views.PostDayArchiveView.as_view(), 
        name='post_day_archive'
    ),
    path(
        'archive/today/', views.PostTodayArchiveView.as_view(), 
        name='post_today_archive'
    ),
    path(
        'tag/', views.TagCloudTemplateView.as_view(), name='tag_cloud'
    ),
    path(
        'tag/<str:tag>/', views.TaggedObjectListView.as_view(), 
        name='tagged_object_list'
    ),
    path(
        'search/', views.SearchFormView.as_view(), name='search'
    ),
    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeListView.as_view(), name='change'),
    path(
        '<int:pk>/update/', views.PostUpdateView.as_view(), name='update'
    ),
    path(
        '<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'
    ),
]

django/django_book1/django_pjt/urls.py
import rest_framework

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import (handler403, handler404, handler500)

import django_app   #NOQA
import django_rest  #NOQA
from programmers_test import urls as p_urls
from programmers_test.views import (error403, error404, error500)
from books.views import HomeView
import bookmark
import blog
import photo
from .views import (UserCreateView, UserCreateDoneTemplateView)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('django_app.urls')),
    path('rest/', include('django_rest.urls')),
    re_path(r'^product\/', include((p_urls.extra_patterns, 'programmers_test')), name='product'),
    re_path(r'^products', include((p_urls.urlpatterns, 'programmers_test')), name='products'),
    path('books/', include('books.urls')),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('api-auth/', include('rest_framework.urls')),  # for adding login to the browsable api
    path('photo/', include('photo.urls')),
    path(
        'accounts/', include('django.contrib.auth.urls')
    ),
    path(
        'accounts/register/', UserCreateView.as_view(), name='register'
    ),
    path(
        'accounts/register/done/', UserCreateDoneTemplateView.as_view(),
        name='register_done'
    ), 
]

# defaults.page_not_found(request, exception, template_name='404.html')
handler403 = error403
handler404 = error404
handler500 = error500

django/django_book1/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField(
        verbose_name='SLUG', unique=True, 
        allow_unicode=True, help_text='one word for title alias.'
    )
    description = models.CharField(
        verbose_name='DESCRIPTION', max_length=100,
        blank=True, help_text='simple decription text.'
    )
    content = models.TextField(verbose_name='CONTENT')
    create_dt = models.DateTimeField(
        verbose_name='CREATE DATE', auto_now_add=True
    )
    modify_dt = models.DateTimeField(
        verbose_name='MODIFY DATE', auto_now=True
    )
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(
        to=User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, 
        null=True
    )
    
    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt', )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        self.slug = (self.slug).replace('-', '_')
        return super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('blog:detail', args=(self.slug,))
    
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    
    def get_next(self):
        return self.get_next_by_modify_dt()

django/django_book1/blog/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search = forms.CharField(label='Search Word')

django/django_book1/blog/views.py
from django.shortcuts import render
from django.views import generic
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post
from .forms import PostSearchForm
from django_pjt.views import OwnerOnlyMixin


# Create your views here.
class PostListView(generic.ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

class PostDetailView(generic.DetailView):
    model = Post

class PostArchiveView(generic.ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'

class PostYearArchiveView(generic.YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True

class PostMonthArchiveView(generic.MonthArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostDayArchiveView(generic.DayArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostTodayArchiveView(generic.TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

class TagCloudTemplateView(generic.TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectListView(generic.ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

class SearchFormView(generic.FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        search = form.cleaned_data['search']
        post_list = Post.objects.filter(
            Q(title__icontains=search) | Q(description__icontains=search) | 
            Q(content__icontains=search)
        ).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = search
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)

class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    fields = [
        'title', 'slug', 'description', 'content', 'tags', 
    ]
    initial = {
        'slug': 'auto-filling-do-not-input', 
    }   # custom message using at Post create view html
    # fields = [
    #     'title', 'description', 'content', 'tags', 
    # ]   # dealing with slug field in another way. don't display slug field.
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PostChangeListView(LoginRequiredMixin, generic.ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(OwnerOnlyMixin, generic.UpdateView):
    model = Post
    fields = [
        'title', 'slug', 'description', 'content', 'tags', 
    ]
    success_url = reverse_lazy('blog:index')

class PostDeleteView(OwnerOnlyMixin, generic.DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

django/django_book1/templates/blog/blog_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>Blog BASE html</title>
    {% endblock %}
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

django/django_book1/templates/blog/post_all.html
{% extends '../books/base.html' %}

{% block title %}
<title>Post All html</title>
{% endblock %}

{% block content %}
<h1>Blog List</h1>
<br />

{% for post in posts %}
    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
    {{ post.modify_dt|date:'N d, Y '}}
    <p>{{ post.description }}</p>
{% endfor %}

<br />

<div>
    <span>
        {% if page_obj.has_previous %}        
            <a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next Page</a>
        {% endif %}
    </span>
</div>

{% endblock %}

django/django_book1/templates/blog/post_archive.html
{% extends '../books/base.html' %}

{% block title %}
<title>Post Archive List html</title>
{% endblock %}

{% block content %}
<h1>Post Archives until {% now 'N d, Y' %}</h1>

<ul>
    {% for date in date_list %}
     <li style="display: inline;">
        <a href="{% url 'blog:post_year_archive' date|date: 'Y' %}">
            Year
        </a>
    </li>
    {% endfor %}
</ul>
<br />

<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_dt|date: 'Y-m-d' }} &nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

django/django_book1/templates/blog/post_archive_day.html
{% extends '../books/base.html' %}

{% block title %}
<title>Post Archive Day HTML</title>
{% endblock %}

{% block content %}
<h1>Post Archives for {{ day|date: 'N d, Y' }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date: 'Y-m-d' }} &nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

django/django_book1/templates/blog/post_archive_month.html
{% extends '../books/base.html' %}

{% block title %}
<title>Post Archive Month HTML</title>
{% endblock %}

{% block content %}
<h1>Post Archives for {{ month|date: 'N, Y' }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date: 'Y-m-d' }} &nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

django/django_book1/templates/blog/post_archive_year.html
{% extends '../books/base.html' %}

{% block title %}
<title>Post Archive Year HTML</title>
{% endblock %}

{% block content %}
<h1>Post Archive for {{ year|date: 'Y' }}</h1>

<ul>
    {% for ddate in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date: 'Y' date|date: 'b' %}">
                {{ date|date: 'F' }}
            </a>
        </li>
    {% endfor %}
</ul>
<br />

<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_dt|date: 'Y-m-d' }} &nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}">
                    <strong>{{ post.title }}</strong>
                </a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

django/django_book1/templates/blog/post_change_list.html
{% extends '../books/base.html' %}

{% block title %}
    <title>Post Change List HTML</title>
{% endblock %}

{% block content %}
    <h1>Post Change - {{ user }}</h1>
    <br />

    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr class="table-primary">
                <th>Title</th>
                <th>Url</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.url }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'post:update' item.id %}">Update</a></td>
                    <td><a href="{% url 'post:delete' item.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

django/django_book1/templates/blog/post_confirm_delete.html
{% extends '../books/base.html' %}

{% block title %}
    <title>Post Confirm Delete HTML</title>
{% endblock %}

{% block content %}
    <h1>Post Delete</h1>
    <br />

    <form action="." method="post"> {% csrf_token %}
        <p>Are you sure you want to delete &ldquo;{{ object }}&rdquo;?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
    </form>
{% endblock %}

django/django_book1/templates/blog/post_detail.html
{% extends '../books/base.html' %}

{% block title %}
<title>Post Detail html</title>
{% endblock %}

{% block content %}
<h2>{{ object.title }}</h2>

<p>
    {% if object.get_previous %}
    <a href="{{ object.get_previous.get_absolute_url }}" title="View next post">
        &laquo; -- {{ object.get_previous }}
    </a>
    {% endif %}

    {% if object.get_next %}
    <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
        {{ object.get_next }} -- &raquo;
    </a>
    {% endif %}
</p>

<p>{{ object.modify_dt|date:'j F Y' }}</p>
<br />

<div>
    {{ object.content|linebreaks }}
</div>

<br />

<div>
    <b>TAGS</b><i class="fas fa-tag"></i>
    {% load taggit_templatetags2_tags %}
    {% get_tags_for_object object as 'tags' %}
    {% for tag in tags %}
    <a href="{% url 'blog:tagged_object_list' tag.name %}">{{ tag.name }}</a>
    {% endfor %}
    <a href="{% url 'blog:tag_cloud' %}">
        <span class="btn btn-info btn-sm">TagCloud</span>
    </a>
</div>
{% endblock %}

django/django_book1/templates/blog/post_form.html
{% extends '../books/base.html' %}

{% load widget_tweaks %}

{% block title %}
    <title>Post Form HTML</title>
{% endblock %}

{% block content %}
    <h1>Post Create/Update = {{ user }}</h1>
    <p class="font-italic">This is as create or update form for your post.</p>

    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
            {{ form.errors }}
        </div>
    {% endif %}

    <form action="." method="post" class="car pt-3">
        <div class="form-group row">
            {{ form.title|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.title|add_class:'form-control'|attr:'autofocus' }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.slug|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.slug|add_class:'form-control'|attr:'readonly' }}
            </div>
            <small class="form-text text-muted">
                {{ form.slug.help_text }}
            </small>
        </div>
        <div class="form-group row">
            {{ form.description|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.description|add_class:'form-control'|attr:'form-control' }}
            </div>
            <small class="form-text text-muted">
                {{ form.description.help_text }}
            </small>
        </div>
        <div class="form-group row">
            {{ form.content|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-8">
                {{ form.content|add_class:'form-control'|attr:'form-control' }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.tags|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.tags|add_class:'form-control'|attr:'form-control' }}
            </div>
            <small class="form-text text-muted">
                {{ form.tags.help_text }}
            </small>
        </div>
        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>
    </form>
{% endblock %}

django/django_book1/templates/blog/post_search.html
{% extends '../books/base.html' %}


{% block title %}
<title>Post Search HTML</title>
{% endblock %}

{% block content %}
<h1>Blog Search</h1>

<br />

<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>

<br />
<br />

{% if object_list %}
    {% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {{ post.modify_date|date:'N d, Y' }}
    <p>{{ post.description }}</p>
    {% endfor %}
{% elif search_term %}
<b><i>Search Word({{ search_term }}) Not Found !</i></b>
{% endif %}
{% endblock %}