django/django_book1/blog/urls.py
from django.urls import (path, re_path)

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    re_path(
        r'^post/(?P<slug>[-\w]+)/$', views.PostDetailView.as_view(), 
        name='post_detail'
    ),   
    path('archive/', views.PostArchiveView.as_view(), name='post_archive'),
    path(
        'archive/<int:year>/', views.PostYearArchiveView.as_view(),
        name='post_year_archive'
    ),
    path(
        'archive/<int:year>/<str:month>/', 
        views.PostMonthArchiveView.as_view(), 
        name='post_month_archive'
    ),
    path(
        'archive/<int:year>/<str:month>/<int:day>/', 
        views.PostDayArchiveView.as_view(), 
        name='post_day_archive'
    ),
    path(
        'archive/today/', views.PostTodayArchiveView.as_view(), 
        name='post_today_archive'
    ),
    path(
        'tag/', views.TagCloudTemplateView.as_view(), name='tag_cloud'
    ),
    path(
        'tag/<str:tag>/', views.TaggedObjectListView.as_view(), 
        name='tagged_object_list'
    ),
    path(
        'search/', views.SearchFormView.as_view(), name='search'
    ),
    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeListView.as_view(), name='change'),
    path(
        '<int:pk>/update/', views.PostUpdateView.as_view(), name='update'
    ),
    path(
        '<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'
    ),
]

django/django_book1/bookmark/urls.py
from django.urls import path

from . import views


app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkListView.as_view(), name='index'),
    path('<int:pk>', views.BookmarkDetailView.as_view(), name='detail'),
    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeListView.as_view(), name='change'),
    path(
        '<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'
    ),
    path(
        '<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'
    ), 
]

django/django_book1/django_pjt/urls.py
import rest_framework

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import (handler403, handler404, handler500)

import django_app   #NOQA
import django_rest  #NOQA
from programmers_test import urls as p_urls
from programmers_test.views import (error403, error404, error500)
from books.views import HomeView
import bookmark
import blog
import photo
from .views import (UserCreateView, UserCreateDoneTemplateView)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('django_app.urls')),
    path('rest/', include('django_rest.urls')),
    re_path(r'^product\/', include((p_urls.extra_patterns, 'programmers_test')), name='product'),
    re_path(r'^products', include((p_urls.urlpatterns, 'programmers_test')), name='products'),
    path('books/', include('books.urls')),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('api-auth/', include('rest_framework.urls')),  # for adding login to the browsable api
    path('photo/', include('photo.urls')),
    path(
        'accounts/', include('django.contrib.auth.urls')
    ),
    path(
        'accounts/register/', UserCreateView.as_view(), name='register'
    ),
    path(
        'accounts/register/done/', UserCreateDoneTemplateView.as_view(),
        name='register_done'
    ), 
]

# defaults.page_not_found(request, exception, template_name='404.html')
handler403 = error403
handler404 = error404
handler500 = error500

django/django_book1/bookmark/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Bookmark(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=100, blank=True)
    url = models.URLField(verbose_name='URL', unique=True)
    owner = models.ForeignKey(
        to=User, on_delete=models.CASCADE, blank=True, null=True
    )
    
    def __str__(self):
        return self.title

django/django_book1/bookmark/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Bookmark
from django_pjt.views import OwnerOnlyMixin


# Create your views here.
class BookmarkListView(generic.ListView):
    model = Bookmark

class BookmarkDetailView(generic.DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, generic.CreateView):
    model = Bookmark
    fields = [
        'title', 'url', 
    ]
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class BookmarkChangeListView(LoginRequiredMixin, generic.ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(OwnerOnlyMixin, generic.UpdateView):
    model = Bookmark
    fields = [
        'title', 'url', 
    ]
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(OwnerOnlyMixin, generic.DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

django/django_book1/templates/bookmark/bookmark_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>Bookmark BASE HTML</title>
    {% endblock %}
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

django/django_book1/templates/bookmark/bookmark_change_list.html
{% extends '../books/base.html' %}

{% block title %}
    <title>Bookmark Change List HTML</title>
{% endblock %}

{% block content %}
    <h1>Bookmark Change - {{ user }}</h1>
    <br />

    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr class="table-primary">
                <th>Title</th>
                <th>Url</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.url }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
                    <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

django/django_book1/templates/bookmark/bookmark_confirm_delete.html
{% extends '../books/base.html' %}

{% block title %}
    <title>Bookmark Confirm Delete HTML</title>
{% endblock %}

{% block content %}
    <h1>Bookmark Delete</h1>
    <br />

    <form action="." method="post"> {% csrf_token %}
        <p>Are you sure you want to delete &ldquo;{{ object }}&rdquo;?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
    </form>
{% endblock %}

django/django_book1/templates/bookmark/bookmark_detail.html
{% extends '../books/base.html' %}

{% block title %}
<title>BookmarkDetailView HTML</title>
{% endblock %}

{% block content %}
<h1>{{ object.title }}</h1>

<ul>
    <li> URL : <a href="{{ object.url }}">{{ object.url }}</a></li>
</ul>
{% endblock %}

django/django_book1/templates/bookmark/bookmark_form.html
{% extends '../books/base.html' %}

{% load widget_tweaks %}

{% block title %}
    <title>Bookmark Form HTML</title>
{% endblock %}

{% block content %}
    <h1>Bookmark Create/Update - {{ user }}</h1>
    <p class="font-italic">This is a create of update form for your bookmark.</p>

    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
            {{ form.errors }}
        </div>
    {% endif %}

    <form action="." method="post" class="card pt-3"> {% csrf_token %}
        <div class="form-group row">
            {{ form.title|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.title|add_class:'form-control'|attr:'autofocus' }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.url|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.url|add_class:'form-control' }}
            </div>
        </div>
        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>
    </form>
{% endblock %}

django/django_book1/templates/bookmark/bookmark_list.html
{% extends '../books/base.html' %}

{% block title %}
<title>BookmarkListView HTML</title>
{% endblock %}

{% block content %}
<h1>Bookmark List</h1>

<ul>
    {% for bookmark in object_list %}
    <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
    {% endfor %}
</ul>
{% endblock %}