django/django_book1/blog/urls.py
from django.urls import (path, re_path)

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    re_path(
        r'^post/(?P<slug>[-\w]+)/$', views.PostDetailView.as_view(), 
        name='post_detail'
    ),   
    path('archive/', views.PostArchiveView.as_view(), name='post_archive'),
    path(
        'archive/<int:year>/', views.PostYearArchiveView.as_view(),
        name='post_year_archive'
    ),
    path(
        'archive/<int:year>/<str:month>/', 
        views.PostMonthArchiveView.as_view(), 
        name='post_month_archive'
    ),
    path(
        'archive/<int:year>/<str:month>/<int:day>/', 
        views.PostDayArchiveView.as_view(), 
        name='post_day_archive'
    ),
    path(
        'archive/today/', views.PostTodayArchiveView.as_view(), 
        name='post_today_archive'
    ),
    path(
        'tag/', views.TagCloudTemplateView.as_view(), name='tag_cloud'
    ),
    path(
        'tag/<str:tag>/', views.TaggedObjectListView.as_view(), 
        name='tagged_object_list'
    ),
    path(
        'search/', views.SearchFormView.as_view(), name='search'
    ),
    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeListView.as_view(), name='change'),
    path(
        '<int:pk>/update/', views.PostUpdateView.as_view(), name='update'
    ),
    path(
        '<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'
    ),
]

django/django_book1/bookmark/urls.py
from django.urls import path

from . import views


app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkListView.as_view(), name='index'),
    path('<int:pk>', views.BookmarkDetailView.as_view(), name='detail'),
    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeListView.as_view(), name='change'),
    path(
        '<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'
    ),
    path(
        '<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'
    ), 
]

django/django_book1/books/urls.py
from django.urls import path

from . import views


app_name = 'books'

urlpatterns = [
    path(
        '', views.BooksModelView.as_view(), name='index'
    ),
    path(
        'book/', views.BookList.as_view(), name='book_list'
    ),
    path(
        'author/', views.AuthorList.as_view(), name='author_list'
    ),
    path(
        'publisher/', views.PublisherList.as_view(), name='publisher_list'
    ),
    path(
        'book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'
    ),
    path(
        'author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'
    ),
    path(
        'publisher/<int:pk>/', views.PublisherDetail.as_view(), 
        name='publisher_detail'
    ),
]

django/django_book1/django_app/urls.py
from django.urls import path
from . import views


app_name = 'django_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django/django_book1/django_pjt/urls.py
import rest_framework

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import (handler403, handler404, handler500)

import django_app   #NOQA
import django_rest  #NOQA
from programmers_test import urls as p_urls
from programmers_test.views import (error403, error404, error500)
from books.views import HomeView
import bookmark
import blog
import photo
from .views import (UserCreateView, UserCreateDoneTemplateView)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('django_app.urls')),
    path('rest/', include('django_rest.urls')),
    re_path(r'^product\/', include((p_urls.extra_patterns, 'programmers_test')), name='product'),
    re_path(r'^products', include((p_urls.urlpatterns, 'programmers_test')), name='products'),
    path('books/', include('books.urls')),
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('api-auth/', include('rest_framework.urls')),  # for adding login to the browsable api
    path('photo/', include('photo.urls')),
    path(
        'accounts/', include('django.contrib.auth.urls')
    ),
    path(
        'accounts/register/', UserCreateView.as_view(), name='register'
    ),
    path(
        'accounts/register/done/', UserCreateDoneTemplateView.as_view(),
        name='register_done'
    ), 
]

# defaults.page_not_found(request, exception, template_name='404.html')
handler403 = error403
handler404 = error404
handler500 = error500

django/django_book1/django_rest/urls.py
from rest_framework import (routers, renderers)
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter

from django.urls import (path, include, re_path,)
from django.conf.urls import url

from . import views


app_name = 'django_rest'

snippet_list = views.SnippetViewSet.as_view(
    {
        'get': 'list',
        'post': 'create',
    }
)
snippet_detail = views.SnippetViewSet.as_view(
    {
        'get': 'retrieve',
        'put': 'update',
        'patch': 'partial_update',
        'delete': 'destroy',
    }
)
snippet_highlight = views.SnippetViewSet.as_view(
    {
        'get': 'highlight'
    },
    renderer_classes =[
        renderers.StaticHTMLRenderer
    ]
)
user_list = views.UserViewSet.as_view(
    {
        'get': 'list',
    }
)
user_detail = views.UserViewSet.as_view(
    {
        'get': 'retrieve',
    }
)



urlpatterns = [
    path('snippets/', views.snippet_list, name='index'),
    path('snippets/<int:pk>/', views.snippet_detail, name='detail'),
    path('snippets/cls/', views.SnippetList.as_view(), name='cls_index'),
    path(
        'snippets/cls/<int:pk>/', views.SnippetDetail.as_view(), 
        name='cls_detail'
    ),
    path(
        'snippets/mxn/', views.SnippetListMixinExplicit.as_view(),
        name='mxn_index'
    ),
    path(
        'snippets/mxn/<int:pk>/', views.SnippetDetailMixinExplicit.as_view(),
        name='mxn_detail'
    ),
    path(
        'snippets/gv/', views.SnippetListMixin.as_view(), name='snippet_list'
    ),
    path(
        'snippets/gv/<int:pk>/', views.SnippetDetailMixin.as_view(),
        name='snippet_detail'
    ),

    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),

    path('', views.api_root, name='api'),
    path(
        'snippets/<int:pk>/highlight/', views.SnippetHighlight.as_view(), 
        name='snippet_highlight'
    ),

    path(
        'snippets/vs/', snippet_list, name='vs_snippet_list'
    ),
    path(
        'snippets/vs/<int:pk>/', snippet_detail, name='vs_snippet_detail'
    ),
    path(
        'snippets/vs/<int:pk>/highlight/', snippet_highlight, 
        name='vs_snippet_highlight'
    ),
    path(
        'users/vs/', user_list, name='vs_user_list'
    ),
    path(
        'users/vs/<int:pk>/', user_detail, name='vs_user_detail'
    )
]

# defaultrouter also generates suffix for .json
router = DefaultRouter()
# router = DefaultRouter(trailing_slash=False)
router.register(r'snippets/router', views.SnippetViewSet)
router.register(r'users/router', views.UserViewSet)

urlpatterns.append(path('', include(router.urls)))

# adding prefix to existing urls with 
# urlpatterns = format_suffix_patterns(urlpatterns)

django/django_book1/photo/urls.py
from django.urls import path

from . import views


app_name = 'photo'

urlpatterns = [
    path('', views.AlbumListView.as_view(), name='index'),
    path('album/', views.AlbumListView.as_view(), name='album_list'),
    path(
        'album/<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'
    ),
    path(
        'photo/<int:pk>/', views.PhotoDetailView.as_view(), name='photo_detail'
    ),
]

django/django_book1/books/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    publication_date = models.DateField()
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    authors = models.ManyToManyField('Author')

    def __str__(self):
        return self.title

class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name
    
class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

django/django_book1/books/views.py
from django.shortcuts import render
from django.views import generic
from django.apps import apps

from .models import Book, Author, Publisher


# Create your views here.
class HomeView(generic.TemplateView):
    template_name = 'books/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['app_list'] = ['django_app', 'books', 'programmers_test']
        dictVerbose = {}
        for app in apps.get_app_configs():
            if 'site-packages' not in app.path:
                dictVerbose[app.label] = app.verbose_name
        context['verbose_dict'] = dictVerbose
        print('\n\n\n HomeView.get_context_data() context >>>>> ', context)
        return context

class BooksModelView(generic.TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        """
        add context data being drawn in the template.
        """
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context

class BookList(generic.ListView):
    model = Book

class AuthorList(generic.ListView):
    model = Author

class PublisherList(generic.ListView):
    model = Publisher

class BookDetail(generic.DetailView):
    model = Book

class AuthorDetail(generic.DetailView):
    model = Author

class PublisherDetail(generic.DetailView):
    model = Publisher

django/django_book1/templates/books/author_detail.html
{% extends './base_books.html' %}

{% block title %}
<title>This is Author Detail</title>
{% endblock title %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.salutation }}</p>
<li>Email : {{ object.email }}</li>
{% endblock content %}

django/django_book1/templates/books/author_list.html
{% extends './base_books.html' %}

{% block title %}
<title>This is Author List</title>
{% endblock title %}

{% block content %}
<h2>Author List</h2>
<ul>
    {% for author in object_list %}
    <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

django/django_book1/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    
    {% block title %}
    <title>This is BASE</title>
    {% endblock %}
    
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
    body {
        padding-top: 90px;
    }
    </style>
    {% block custom_css %}
    {% endblock %}
    
</head>
<body>
    <!-- <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Project_Home</a></li>
            <li><a href="/admin/">Admin</a></li>
        </ul>
        {% endblock sidebar %}
        <br />
    </div> -->
    
    <nav class="navbar navbar-expand navbar-light bg-primary fixed-top flex-column flex-md-row bd-navbar">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django Python Web Programming</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active mx-1 btn btn-primary">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
            <a class="nav-link" href="{% url 'bookmark:index' %}">Bookmark</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
            <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
            <a class="nav-link" href="{% url 'photo:index' %}">Photo</a>
        </li>
        <li class="nav-item dropdown mx-1 btn btn-primary">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
            Add
          </a>
          <div class="dropdown-menu">
            <a href="{% url 'bookmark:add' %}" class="dropdown-item">Bookmark</a>
            <a href="{% url 'blog:add' %}" class="dropdown-item">Post</a>
            <div class="dropdown-divider"></div>
            <a href="" class="dropdown-item">Album</a>
            <a href="" class="dropdown-item">Photo</a>
          </div>
        </li>
        <li class="nav-item dropdown mx-1 btn btn-primary">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
            Change
          </a>
          <div class="dropdown-menu">
            <a href="{% url 'bookmark:change' %}" class="dropdown-item">Bookmark</a>
            <a href="{% url 'blog:change' %}" class="dropdown-item">Post</a>
            <div class="dropdown-divider"></div>
            <a href="" class="dropdown-item">Album</a>
            <a href="" class="dropdown-item">Photo</a>
          </div>
        </li>
        <li class="nav-item mx-1 dropdown btn btn-primary">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Util
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0"> {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
      </form>

      <ul class="navbar-nav ml-5 mr-5">
        <li class="nav-item dropdown mx-1 btn btn-primary">
          {% if user.is_active %}
            <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
              <i class="fas fa-user"></i>
              &ensp; {% firstof user.get_short_name user.get_username %}&ensp;
            </a>
            <div class="dropdown-menu">
              <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
              <a href="{% url 'password_change' %}" class="dropdown-item">Change Password</a>
            </div>
          {% else %}
            <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
              <i class="fas fa-user"></i>
              &ensp;Anonymous&ensp;
            </a>
            <div class="dropdown-menu">
              <a href="{% url 'login' %}" class="dropdown-item">Login</a>
              <a href="{% url 'register' %}" class="dropdown-item">Register</a>
            </div>
          {% endif %}
        </li>
      </ul>
    </div>
    </nav>

    <div id="container content">
        {% block content %}
        <h1>books/base.html</h1>
        {% endblock content %}
    </div>

    {% block footer %}
    {% endblock%}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


    {% block custom_script %}
    {% endblock %}
</body>
</html>

django/django_book1/templates/books/base_books.html
{% extends "./base.html" %}

{% block title %}
<title>Books Application Site</title>
{% endblock title %}

{% block sidebar %}
{{block.super}}
<ul>
    <li><a href="/books/">Books_Hmoe</a></li>
</ul>
{% endblock sidebar %}

django/django_book1/templates/books/book_detail.html
{% extends './base_books.html' %}

{% block title %}
<title>This is Book Detail</title>
{% endblock title %}

{% block content %}
<h1>{{ object.title }}</h1>
<br/>
<ul>
    <li>Authors : 
        {% for author in object.authors.all %}
        {{ author }}
        {% if not forloop.last %}
        ,
        {% else %}
        {% endif %}
        {% endfor %}
    </li>
    <li>Publisher : {{ object.publisher }}</li>
    <li>Publication date : {{ object.publication_date }}</li>
</ul>
{% endblock content %}

django/django_book1/templates/books/book_list.html
{% extends './base_books.html' %}

{% block title %}
<title>This is Book List</title>
{% endblock title %}

{% block content %}
<h2>Book List</h2>
<ul>
    {% for book in object_list %}
        <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

django/django_book1/templates/books/home.html
{% extends './base.html' %}
{% load static %}


{% block title %}
<title>This is HOME</title>
{% endblock title %}

{% block custom_css %}
<style>
.home_image {
    background-image: url("{% static 'img/lion.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
<div class="home_image">
    <h2 class="title">Django - Python Web Programming</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
</div>

<hr style="margin: 10px 0;">

<div class="row text-center">
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p>bla blask</p>
    </div>
    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p>blads saf;fla</p>
    </div>
</div>

<h2>shkim Django Applications</h2>
<ul>
<li><a href="{% url 'programmers_test:details' id=17 %}">TEST</a></li>
<li><a href="{% url 'books:index' %}">TEST1</a></li>
<li><a href="{% url 'django_app:index' %}">TEST2</a></li>
<li><a href="{% url 'django_rest:index' %}">TEST3</a></li>
<li><a href="{% url 'programmers_test:index' %}">TEST4</a></li>
</ul>

<ul>
    {% for appname in app_list %}
        {% with appname|add:':index' as urlvar %}
        <li><a href="{% url urlvar %}">{{ appname }}</a></li>
        {% endwith %}
    {% endfor %}
</ul>
<ul>
    {% for key, value in verbose_dict.items %}
    <li><a href="{% url key|add:':index' %}">{{ value }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook</div>
</footer>
{% endblock %}

django/django_book1/templates/books/index.html
{% extends './base_books.html' %}

{% block title %}
<title>Books Index</title>
{% endblock title %}

{% block content %}
<h2>Books Management System</h2>
<ul>
    {% for modelname in model_list %}
        {% with 'books:'|add:modelname|lower|add:'_list' as urlvar %}
        <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
        {% endwith %}
    {% endfor %}
</ul>
{% endblock content %}

django/django_book1/templates/books/publisher_detail.html
{% extends './base_books.html' %}

{% block title %}
<title>This is Publisher Detail</title>
{% endblock title %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.website }}</p>
<li>Address : {{ object.address }}</li>
{% endblock content %}

django/django_book1/templates/books/publisher_list.html
{% extends './base_books.html' %}

{% block title %}
<title>This is Publisher List</title>
{% endblock title %}

{% block content %}
<h2>Publisher List</h2>
<ul>
    {% for author in object_list %}
    <li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

django/django_book1/templates/books/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>*********************</h1>
</body>
</html>